### ISSUE TITLE
关于计算裁剪宽度中镂空80是什么意思？

### ISSUE THREAD

**Issue by LingCn** [leeenx/puzzle#1]
![image](https://user-images.githubusercontent.com/22288787/54669945-8811f300-4b2d-11e9-9c87-619dedadf09d.png)

**Comment by leeenx** [comment]
@NBAUser 指的是这张图片：https://github.com/leeenx/puzzle/blob/master/src/images/clipart.png

![image](https://user-images.githubusercontent.com/8177724/54680047-d7631e00-4b43-11e9-91b0-6f8e8d44775c.png)

其实应该取 60 的，但是取 60 之后，没达到理想效果。当时写完没有时间去研究原因。有兴趣可以研究一下

**Comment by LingCn** [comment]
好的谢谢！
